/** Generated types and spec from the reviewed fade_market.wasm. No deployment or signing client. */
import { Buffer } from 'buffer';
import { Spec } from '@stellar/stellar-sdk/contract';
import type { u32,u64,i128,Option } from '@stellar/stellar-sdk/contract';
export const Errors = {
  1: {message:"NotFound"},
  2: {message:"InvalidState"},
  3: {message:"InvalidTerms"},
  4: {message:"InvalidWindow"},
  5: {message:"BadKey"},
  6: {message:"WrongEpoch"},
  7: {message:"WrongSequence"},
  8: {message:"PriceExceeded"},
  9: {message:"ActiveReservation"},
  10: {message:"UnknownAsset"},
  11: {message:"InvalidDestination"},
  12: {message:"Overflow"},
  13: {message:"Accounting"},
  14: {message:"ArchiveUnavailable"},
  15: {message:"WrongNetwork"},
  16: {message:"Unauthorized"}
}


export interface Offer {
  deadline_ledger: u32;
  id: u64;
  reservation: ReservationState;
  seller: string;
  /**
 * Monotonic across cancellation/expiry; old permits cannot return.
 */
sequence: u64;
  settled_price: Option<i128>;
  settled_to: Option<string>;
  start_ledger: u32;
  /**
 * 0 open, 1 reserved, 2 settled, 3 refunded.
 */
state: u32;
  terms: OfferTerms;
  terms_hash: Buffer;
}


export interface Merchant {
  epoch: u32;
  public_key: Buffer;
  seller: string;
}


export interface ActiveSlot {
  lease_until: u32;
  offer_id: u64;
  sequence: u64;
}


/**
 * Immutable creation terms. Zero lease_ledgers disables remote reservations.
 * metadata_hash commits the separately signed shop/product/pickup description.
 */
export interface OfferTerms {
  asset: string;
  duration_ledgers: u32;
  floor_price: i128;
  lease_ledgers: u32;
  metadata_hash: Buffer;
  pot: i128;
  slope_den: i128;
  slope_num: i128;
  start_price: i128;
}


export interface Reservation {
  claimant: string;
  claimed_at: u32;
  lease_until: u32;
  merchant: Merchant;
  price: i128;
  sequence: u64;
}


export interface MarketConfig {
  assets: Array<string>;
  max_lease_ledgers: u32;
  max_offer_ledgers: u32;
  max_receipt_ledgers: u32;
}



export interface PickupReceipt {
  claimant: string;
  key_epoch: u32;
  /**
 * price <= max_price; a negative bound requires at least that reward.
 */
max_price: i128;
  nonce: Buffer;
  offer_id: u64;
  sequence: u64;
  terms_hash: Buffer;
  valid_from: u32;
  valid_until: u32;
}

export type ReservationState = {tag: "Empty", values: void} | {tag: "Active", values: readonly [Reservation]};


export interface ReservationPermit {
  lease_until: u32;
  receipt: PickupReceipt;
}



export const MARKET_SPEC_ENTRIES=[ "AAAAAAAAAAAAAAAFcHJpY2UAAAAAAAABAAAAAAAAAAhvZmZlcl9pZAAAAAYAAAABAAAD6QAAAAsAAAAD",
        "AAAAAAAAAAAAAAAGcmVmdW5kAAAAAAABAAAAAAAAAAhvZmZlcl9pZAAAAAYAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAAAAAAAAHcmVzZXJ2ZQAAAAACAAAAAAAAAAZwZXJtaXQAAAAAB9AAAAARUmVzZXJ2YXRpb25QZXJtaXQAAAAAAAAAAAAACXNpZ25hdHVyZQAAAAAAA+4AAABAAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAAAAAAAJZ2V0X29mZmVyAAAAAAAAAQAAAAAAAAAIb2ZmZXJfaWQAAAAGAAAAAQAAA+kAAAfQAAAABU9mZmVyAAAAAAAAAw==",
        "AAAAAAAAAAAAAAAKZ2V0X2FjdGl2ZQAAAAAAAgAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAAAhjbGFpbWFudAAAABMAAAABAAAD6AAAB9AAAAAKQWN0aXZlU2xvdAAA",
        "AAAAAAAAAAAAAAAKZ2V0X2NvbmZpZwAAAAAAAAAAAAEAAAPpAAAH0AAAAAxNYXJrZXRDb25maWcAAAAD",
        "AAAAAAAAAAAAAAAMY3JlYXRlX29mZmVyAAAAAgAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAAAV0ZXJtcwAAAAAAB9AAAAAKT2ZmZXJUZXJtcwAAAAAAAQAAA+kAAAAGAAAAAw==",
        "AAAAAAAAAAAAAAAMZ2V0X21lcmNoYW50AAAAAQAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAQAAA+kAAAfQAAAACE1lcmNoYW50AAAAAw==",
        "AAAAAAAAAAAAAAANX19jb25zdHJ1Y3RvcgAAAAAAAAEAAAAAAAAACmFzc2V0X3hkcnMAAAAAA+oAAAAOAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAAAAAAAOc2V0dGxlX3dhbGtfaW4AAAAAAAIAAAAAAAAAB3JlY2VpcHQAAAAH0AAAAA1QaWNrdXBSZWNlaXB0AAAAAAAAAAAAAAlzaWduYXR1cmUAAAAAAAPuAAAAQAAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAAAAAAAPc2V0dGxlX3Jlc2VydmVkAAAAAAIAAAAAAAAAB3JlY2VpcHQAAAAH0AAAAA1QaWNrdXBSZWNlaXB0AAAAAAAAAAAAAAlzaWduYXR1cmUAAAAAAAPuAAAAQAAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAAAAAAAQcHJvdG9jb2xfdmVyc2lvbgAAAAAAAAABAAAABA==",
        "AAAAAAAAAAAAAAAQcmVzZXJ2ZWRfYmFsYW5jZQAAAAEAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAEAAAPpAAAACwAAAAM=",
        "AAAAAAAAAAAAAAARcmVnaXN0ZXJfbWVyY2hhbnQAAAAAAAACAAAAAAAAAAZzZWxsZXIAAAAAABMAAAAAAAAACnB1YmxpY19rZXkAAAAAA+4AAAAgAAAAAQAAA+kAAAfQAAAACE1lcmNoYW50AAAAAw==",
        "AAAAAAAAAAAAAAASY2FuY2VsX3Jlc2VydmF0aW9uAAAAAAADAAAAAAAAAAhvZmZlcl9pZAAAAAYAAAAAAAAACGNsYWltYW50AAAAEwAAAAAAAAAIc2VxdWVuY2UAAAAGAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAAAAAAASZXhwaXJlX3Jlc2VydmF0aW9uAAAAAAABAAAAAAAAAAhvZmZlcl9pZAAAAAYAAAABAAAD6QAAAAIAAAAD",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAAEAAAAAAAAAAITm90Rm91bmQAAAABAAAAAAAAAAxJbnZhbGlkU3RhdGUAAAACAAAAAAAAAAxJbnZhbGlkVGVybXMAAAADAAAAAAAAAA1JbnZhbGlkV2luZG93AAAAAAAABAAAAAAAAAAGQmFkS2V5AAAAAAAFAAAAAAAAAApXcm9uZ0Vwb2NoAAAAAAAGAAAAAAAAAA1Xcm9uZ1NlcXVlbmNlAAAAAAAABwAAAAAAAAANUHJpY2VFeGNlZWRlZAAAAAAAAAgAAAAAAAAAEUFjdGl2ZVJlc2VydmF0aW9uAAAAAAAACQAAAAAAAAAMVW5rbm93bkFzc2V0AAAACgAAAAAAAAASSW52YWxpZERlc3RpbmF0aW9uAAAAAAALAAAAAAAAAAhPdmVyZmxvdwAAAAwAAAAAAAAACkFjY291bnRpbmcAAAAAAA0AAAAAAAAAEkFyY2hpdmVVbmF2YWlsYWJsZQAAAAAADgAAAAAAAAAMV3JvbmdOZXR3b3JrAAAADwAAAAAAAAAMVW5hdXRob3JpemVkAAAAEA==",
        "AAAAAQAAAAAAAAAAAAAABU9mZmVyAAAAAAAACwAAAAAAAAAPZGVhZGxpbmVfbGVkZ2VyAAAAAAQAAAAAAAAAAmlkAAAAAAAGAAAAAAAAAAtyZXNlcnZhdGlvbgAAAAfQAAAAEFJlc2VydmF0aW9uU3RhdGUAAAAAAAAABnNlbGxlcgAAAAAAEwAAAEBNb25vdG9uaWMgYWNyb3NzIGNhbmNlbGxhdGlvbi9leHBpcnk7IG9sZCBwZXJtaXRzIGNhbm5vdCByZXR1cm4uAAAACHNlcXVlbmNlAAAABgAAAAAAAAANc2V0dGxlZF9wcmljZQAAAAAAA+gAAAALAAAAAAAAAApzZXR0bGVkX3RvAAAAAAPoAAAAEwAAAAAAAAAMc3RhcnRfbGVkZ2VyAAAABAAAACowIG9wZW4sIDEgcmVzZXJ2ZWQsIDIgc2V0dGxlZCwgMyByZWZ1bmRlZC4AAAAAAAVzdGF0ZQAAAAAAAAQAAAAAAAAABXRlcm1zAAAAAAAH0AAAAApPZmZlclRlcm1zAAAAAAAAAAAACnRlcm1zX2hhc2gAAAAAA+4AAAAg",
        "AAAAAQAAAAAAAAAAAAAACE1lcmNoYW50AAAAAwAAAAAAAAAFZXBvY2gAAAAAAAAEAAAAAAAAAApwdWJsaWNfa2V5AAAAAAPuAAAAIAAAAAAAAAAGc2VsbGVyAAAAAAAT",
        "AAAAAQAAAAAAAAAAAAAACkFjdGl2ZVNsb3QAAAAAAAMAAAAAAAAAC2xlYXNlX3VudGlsAAAAAAQAAAAAAAAACG9mZmVyX2lkAAAABgAAAAAAAAAIc2VxdWVuY2UAAAAG",
        "AAAAAQAAAJdJbW11dGFibGUgY3JlYXRpb24gdGVybXMuIFplcm8gbGVhc2VfbGVkZ2VycyBkaXNhYmxlcyByZW1vdGUgcmVzZXJ2YXRpb25zLgptZXRhZGF0YV9oYXNoIGNvbW1pdHMgdGhlIHNlcGFyYXRlbHkgc2lnbmVkIHNob3AvcHJvZHVjdC9waWNrdXAgZGVzY3JpcHRpb24uAAAAAAAAAAAKT2ZmZXJUZXJtcwAAAAAACQAAAAAAAAAFYXNzZXQAAAAAAAATAAAAAAAAABBkdXJhdGlvbl9sZWRnZXJzAAAABAAAAAAAAAALZmxvb3JfcHJpY2UAAAAACwAAAAAAAAANbGVhc2VfbGVkZ2VycwAAAAAAAAQAAAAAAAAADW1ldGFkYXRhX2hhc2gAAAAAAAPuAAAAIAAAAAAAAAADcG90AAAAAAsAAAAAAAAACXNsb3BlX2RlbgAAAAAAAAsAAAAAAAAACXNsb3BlX251bQAAAAAAAAsAAAAAAAAAC3N0YXJ0X3ByaWNlAAAAAAs=",
        "AAAAAQAAAAAAAAAAAAAAC1Jlc2VydmF0aW9uAAAAAAYAAAAAAAAACGNsYWltYW50AAAAEwAAAAAAAAAKY2xhaW1lZF9hdAAAAAAABAAAAAAAAAALbGVhc2VfdW50aWwAAAAABAAAAAAAAAAIbWVyY2hhbnQAAAfQAAAACE1lcmNoYW50AAAAAAAAAAVwcmljZQAAAAAAAAsAAAAAAAAACHNlcXVlbmNlAAAABg==",
        "AAAAAQAAAAAAAAAAAAAADE1hcmtldENvbmZpZwAAAAQAAAAAAAAABmFzc2V0cwAAAAAD6gAAABMAAAAAAAAAEW1heF9sZWFzZV9sZWRnZXJzAAAAAAAABAAAAAAAAAARbWF4X29mZmVyX2xlZGdlcnMAAAAAAAAEAAAAAAAAABNtYXhfcmVjZWlwdF9sZWRnZXJzAAAAAAQ=",
        "AAAABQAAAAAAAAAAAAAADE9mZmVyQ2hhbmdlZAAAAAEAAAANb2ZmZXJfY2hhbmdlZAAAAAAAAAYAAAAAAAAACG9mZmVyX2lkAAAABgAAAAEAAAAAAAAABXN0YXRlAAAAAAAABAAAAAAAAAAAAAAACHNlcXVlbmNlAAAABgAAAAAAAAAAAAAABmxlZGdlcgAAAAAABAAAAAAAAAAAAAAACGNsYWltYW50AAAD6AAAABMAAAAAAAAAAAAAAAVwcmljZQAAAAAAA+gAAAALAAAAAAAAAAI=",
        "AAAAAQAAAAAAAAAAAAAADVBpY2t1cFJlY2VpcHQAAAAAAAAJAAAAAAAAAAhjbGFpbWFudAAAABMAAAAAAAAACWtleV9lcG9jaAAAAAAAAAQAAABDcHJpY2UgPD0gbWF4X3ByaWNlOyBhIG5lZ2F0aXZlIGJvdW5kIHJlcXVpcmVzIGF0IGxlYXN0IHRoYXQgcmV3YXJkLgAAAAAJbWF4X3ByaWNlAAAAAAAACwAAAAAAAAAFbm9uY2UAAAAAAAPuAAAAIAAAAAAAAAAIb2ZmZXJfaWQAAAAGAAAAAAAAAAhzZXF1ZW5jZQAAAAYAAAAAAAAACnRlcm1zX2hhc2gAAAAAA+4AAAAgAAAAAAAAAAp2YWxpZF9mcm9tAAAAAAAEAAAAAAAAAAt2YWxpZF91bnRpbAAAAAAE",
        "AAAAAgAAAAAAAAAAAAAAEFJlc2VydmF0aW9uU3RhdGUAAAACAAAAAAAAAAAAAAAFRW1wdHkAAAAAAAABAAAAAAAAAAZBY3RpdmUAAAAAAAEAAAfQAAAAC1Jlc2VydmF0aW9uAA==",
        "AAAAAQAAAAAAAAAAAAAAEVJlc2VydmF0aW9uUGVybWl0AAAAAAAAAgAAAAAAAAALbGVhc2VfdW50aWwAAAAABAAAAAAAAAAHcmVjZWlwdAAAAAfQAAAADVBpY2t1cFJlY2VpcHQAAAA=",
        "AAAABQAAAAAAAAAAAAAAEk1lcmNoYW50UmVnaXN0ZXJlZAAAAAAAAQAAABNtZXJjaGFudF9yZWdpc3RlcmVkAAAAAAMAAAAAAAAABnNlbGxlcgAAAAAAEwAAAAEAAAAAAAAACnB1YmxpY19rZXkAAAAAA+4AAAAgAAAAAAAAAAAAAAAFZXBvY2gAAAAAAAAEAAAAAAAAAAI=" ] as const;
export const marketSpec=new Spec([...MARKET_SPEC_ENTRIES]);
