import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire, registerHooks } from 'node:module';
import { createStateFixture } from './helpers/public-lifecycle-state-fixture.mjs';
const { xdr, Account, Address, Contract, TransactionBuilder } = createRequire(new URL('../../app/package.json', import.meta.url))('@stellar/stellar-sdk');
const real = process.env.PUBLIC_LIFECYCLE_STATE_WASM === '1';
// Default algorithm tests retain the actual structural decoder and replace ONLY
// its unavailable-on-clean-CI executable-byte gate. Opt-in runs identical cases
// against the reviewed compiled artifact, without any production hash override.
const readbackURL = new URL('../lib/public-lifecycle-readback.mjs', import.meta.url).href;
const callURL = new URL('../lib/public-lifecycle-call.mjs', import.meta.url).href;
// Count the real call builder at the state boundary; no behavior is replaced.
const countedCallURL = 'data:text/javascript,' + encodeURIComponent(`import * as actual from ${JSON.stringify(callURL)};export {bindPublicLifecycleCall} from ${JSON.stringify(callURL)};export let count=0;export function publicLifecycleCallIntent(value){count++;return actual.publicLifecycleCallIntent(value);}`);
const hook = registerHooks({ resolve(specifier, context, next) {
  if (specifier === './public-lifecycle-call.mjs' && context.parentURL?.endsWith('/public-lifecycle-state.mjs')) return {url:countedCallURL,shortCircuit:true};
  if (!real && specifier === './public-lifecycle-readback.mjs' && context.parentURL?.endsWith('/public-lifecycle-state.mjs')) return { url: 'data:text/javascript,' + encodeURIComponent(`import {verifyPublicLifecycleState} from ${JSON.stringify(readbackURL)}; export function verifyPublicLifecycleSnapshot(a,b){return {...verifyPublicLifecycleState(a,b),schema:'agyion-public-v4-lifecycle-snapshot-v1',codeBytesAuthenticated:true};}`), shortCircuit: true };
  return next(specifier, context);
} });
const { initialPublicLifecycleState, derivePublicLifecycleState, verifyPublicLifecycleHeader, assertPublicLifecycleDerivedState } = await import('../lib/public-lifecycle-state.mjs');
hook.deregister();
const countedCalls = await import(countedCallURL);
const label = real ? 'actual pinned WASM' : 'unit executable-auth-only double';
const fixture = createStateFixture({realWasm:real});
const {plan,roles,accounts,account,header,snapshot,b64,int,en,clone} = fixture;
const stateFns={initialPublicLifecycleState,derivePublicLifecycleState};
const boot=(response=snapshot(),h=header())=>fixture.boot(stateFns,response,h);
const journey=stop=>fixture.journey(stateFns,stop);

test(`${label}: bootstrap budget needs no future transaction or credential construction`,()=>{
  const prior=countedCalls.count, initial=boot();
  assert.equal(initial.remainingBudget.seller.grossOutflowStroops,'130000001');
  assert.equal(countedCalls.count-prior,0,'Remaining funds must not rebuild future calls and revalidate the entire plan for each one');
});

test(`${label}: all78 remaining budgets match independent cash-flow and fee-payer timeline`,()=>{
  const j=journey(), sources=['SRLSRL','RRSRR','SRSLS','LSLSRL','SLLRR','SRRL','SSSSRLRL'].join('').split('');
  assert.equal(sources.length,39);
  const roleOf={S:'seller',R:'recipient',L:'relayer'};
  for(let i=0;i<39;i++)for(const [phase,state,from]of [['before',j.stages[i].pre,i],['after',j.stages[i].post,i+1]]){
    for(const [column,role]of roles.entries()){
      const gross=fixture.business.slice(from).reduce((sum,deltas)=>sum+BigInt(Math.max(0,-(deltas[column]??0))),0n);
      const transactions=sources.slice(from).filter(source=>roleOf[source]===role).length, fees=BigInt(transactions)*10000000n;
      assert.deepEqual(state.remainingBudget[role],{grossOutflowStroops:String(gross),transactions,feeCeilingStroops:String(fees),minimumBalanceStroops:'10000000',requiredStroops:String(gross+fees+10000000n)},`${i+1} ${phase} ${role}`);
    }
  }
});

test(`${label}: bootstrap derives empty expectations, reserve and conservative role budgets from raw data`,()=>{const s=boot();assert.deepEqual(s?.expected.records,[]);assert.equal(s.reserve.minimumBalanceStroops,'10000000');assert.deepEqual(Object.fromEntries(roles.map(r=>[r,s.remainingBudget[r].requiredStroops])),{seller:'280000001',recipient:'151000000',relayer:'120000000'});assert.equal(s.expected.initialSurplusStroops,'0');const surplus=boot(snapshot(1000,[],accounts(),'7'));assert.equal(surplus.expected.initialSurplusStroops,'7');});
test(`${label}: all39 exact transitions include source-only sequence, donation, original IDs and final balances`,()=>{const j=journey(),s=j.stages.at(-1).post;assert.deepEqual(s.snapshot.counters,{Fade:'8',Pod:'2',Trigger:'3',Mandate:'3'});assert.deepEqual(s.snapshot.liabilities.map(v=>v.amount),['0','0']);assert.equal(s.snapshot.nativeReserveStroops,'1');assert.deepEqual(Object.fromEntries(roles.map(r=>[r,j.as[r].sequence])),{seller:'24',recipient:'24',relayer:'21'});assert.deepEqual(Object.fromEntries(roles.map(r=>[r,j.as[r].balance])),{seller:'958998599',recipient:'1040998600',relayer:'999998900'});assert.equal(s.recordAnchors.find(r=>r.record==='fade-no-show').value.claimant,plan.actors.recipient);assert.equal(s.recordAnchors.find(r=>r.record==='fade-no-show').value.claimed_at,1092);assert.equal(s.recordAnchors.find(r=>r.record==='grant-capped').value.claims_used,1);assert.equal(s.recordAnchors.find(r=>r.record==='grant-expiry').value.revoked,false);assert.equal(assertPublicLifecycleDerivedState(s),s);assert.throws(()=>assertPublicLifecycleDerivedState(clone(s)),/BRAND/);});
test('same-ledger latest and history headers produce identical independently hashed reserve evidence',()=>{assert.deepEqual(verifyPublicLifecycleHeader({headerEvidence:header(),ledger:1000}),verifyPublicLifecycleHeader({headerEvidence:header(1000,'history'),ledger:1000}));assert.equal(verifyPublicLifecycleHeader({headerEvidence:header(1000,'latest',7000000),ledger:1000}).minimumBalanceStroops,'14000000');});
for(const [name,mutate]of [['wrong ledger',x=>x.ledger++],['wrong hash',x=>x.hash='00'.repeat(32)],['wrong variant',x=>x.kind='history'],['noncanonical XDR',x=>x.headerXdr+='\n'],['oversized XDR',x=>x.headerXdr='A'.repeat(20000)],['unknown property',x=>x.expectedReserve='1'],['accessor',x=>Object.defineProperty(x,'ledger',{get(){throw Error('must not invoke');},enumerable:true})]])test(`header rejects ${name}`,()=>{const h=header();mutate(h);assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:h,ledger:1000}),/LIFECYCLE_STATE_/);});
for(const [name,mutate]of [['missing account',r=>r.entries.splice(7,1)],['duplicate account',r=>r.entries.push(r.entries[7])],['nonempty counter',r=>{const v=xdr.LedgerEntryData.fromXDR(r.entries[1].val,'base64');v.contractData().val().instance().storage().push(new xdr.ScMapEntry({key:en('FadeCount'),val:int(1,'u64')}));r.entries[1].val=b64(v);}],['nonzero liability',r=>{const v=xdr.LedgerEntryData.fromXDR(r.entries[4].val,'base64');v.contractData().val(int(1));r.entries[4].val=b64(v);}],['unfunded actor',r=>{const v=xdr.LedgerEntryData.fromXDR(r.entries[8].val,'base64');v.account().balance(xdr.Int64.fromString('150999999'));r.entries[8].val=b64(v);}],['untrusted accessor',r=>Object.defineProperty(r,'latestLedger',{get(){throw Error('do not evaluate');},enumerable:true})]])test(`${label}: bootstrap refuses ${name}`,()=>{const r=snapshot();mutate(r);assert.throws(()=>boot(r),/LIFECYCLE_/);});
test(`${label}: finite funds threshold is inclusive but one stroop below refuses future-credit financing`,()=>{const as=accounts();for(const[r,v]of Object.entries({seller:'280000001',recipient:'151000000',relayer:'120000000'})){as[r].balance=v;as[r].accountEntryXdr=b64(account(r,v));}assert.ok(boot(snapshot(1000,[],as)));as.recipient.balance='150999999';as.recipient.accountEntryXdr=b64(account('recipient','150999999'));assert.throws(()=>boot(snapshot(1000,[],as)),/FUNDS/);});
for(const[name,mutate]of [['wrong created ID',v=>v.inclusion.createdId='2'],['failed inclusion',v=>v.inclusion.status='FAILED'],['creation at preparation head',v=>v.inclusion.ledger=v.binding.headLedger],['serialized initial',v=>v.initial=clone(v.initial)],['changed signed args',v=>v.binding.argsXdr[3]=b64(int(0))],['wrong source sequence',v=>v.binding.sequence='12']])test(`${label}: refuses ${name}`,()=>{const j=journey(1),v={...j.stages[0].after,binding:clone(j.stages[0].after.binding),inclusion:clone(j.stages[0].after.inclusion)};mutate(v);assert.throws(()=>derivePublicLifecycleState(v),/LIFECYCLE_/);});
for(const[name,mutate]of [['outside credit',v=>{const r=v.response.entries[8],d=xdr.LedgerEntryData.fromXDR(r.val,'base64');d.account().balance(xdr.Int64.fromString('1000000001'));r.val=b64(d);}],['prefix net-fee mismatch',v=>v.prefix[0].fee.netFee='101'],['missing predecessor',v=>v.prefix=[]],['foreign predecessor',v=>v.prefix[0].stepId=plan.steps[3].id],['regressed prior after head',v=>v.prefix[0].after.ledger=v.binding.headLedger+1]])test(`${label}: rejects ${name} before next preparation`,()=>{const j=journey(2),v={...j.stages[1].before,prefix:clone(j.stages[1].before.prefix),response:clone(j.stages[1].before.response)};mutate(v);assert.throws(()=>derivePublicLifecycleState(v),/LIFECYCLE_/);});
for(const[index,name,ledger,code]of [[12,'Pod before unlock',1051,'UNLOCK'],[16,'Trigger refund at deadline',1070,'REFUND_WINDOW'],[18,'Fade refund at deadline',1086,'REFUND_WINDOW'],[21,'claimed Fade refund at handoff deadline',1104,'REFUND_WINDOW'],[14,'attest after deadline',1175,'ATTEST_WINDOW'],[2,'handoff after window',1064,'HANDOFF_WINDOW']])test(`${label}: rejects impossible ${name} even if a later snapshot looks terminal`,()=>{const j=journey(index+1),v={...j.stages[index].after,binding:clone(j.stages[index].after.binding),inclusion:clone(j.stages[index].after.inclusion),response:clone(j.stages[index].after.response)};v.inclusion.ledger=ledger;v.binding.headLedger=Math.min(v.binding.headLedger,ledger-1);v.response.latestLedger=Math.max(v.response.latestLedger,ledger);v.headerEvidence=header(v.response.latestLedger);assert.throws(()=>derivePublicLifecycleState(v),new RegExp('LIFECYCLE_STATE_'+code));});
test('actual full bootstrap byte-authentication pipeline is explicitly opt-in', {skip:!real},()=>{assert.equal(boot().snapshot.codeBytesAuthenticated,true);});

test('unmocked bootstrap rejects synthetic code bytes even when every other snapshot field matches',async()=>{const actual=await import('../lib/public-lifecycle-state.mjs?real-byte-rejection');const response=snapshot();const v=xdr.LedgerEntryData.fromXDR(response.entries[0].val,'base64');v.contractCode().code(Buffer.from('SYNTHETIC INVALID CODE'));response.entries[0].val=b64(v);assert.throws(()=>actual.initialPublicLifecycleState({plan,response,zeroBalanceEvidence:null,headerEvidence:header()}),/CODE_BYTES/);});
test('zero reserve, same-sized wrong history hash, forged ledger number and raw hostile header proxy all fail closed',()=>{assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:header(1000,'latest',0),ledger:1000}),/HEADER_RESERVE/);const h=header(1000,'history'),v=xdr.LedgerHeaderHistoryEntry.fromXDR(h.headerXdr,'base64');v.hash(Buffer.alloc(32));h.headerXdr=b64(v);assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:h,ledger:1000}),/HEADER_HISTORY/);const wrong=header(999);wrong.ledger=1000;assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:wrong,ledger:1000}),/HEADER_HASH/);assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:new Proxy({},{ownKeys(){throw Error('untrusted secret-looking text');}}),ledger:1000}),e=>e.message==='LIFECYCLE_STATE_INPUT');});
test(`${label}: current before record metadata cannot predate the included transition`,()=>{const j=journey(3),v={...j.stages[2].before,response:clone(j.stages[2].before.response)};v.response.entries[10].lastModifiedLedgerSeq=1001;assert.throws(()=>derivePublicLifecycleState(v),/TRANSITION_METADATA/);});
test('hostile parser exception cannot smuggle a trusted-looking diagnostic prefix',()=>{const hostile=new Proxy({},{ownKeys(){throw Error('LIFECYCLE_STATE_private-attacker-content');}});assert.throws(()=>verifyPublicLifecycleHeader({headerEvidence:hostile,ledger:1000}),e=>e.message==='LIFECYCLE_STATE_INPUT');});

test(`${label}: absent initial native balance needs exact same-head zero evidence and never caller expectations`,()=>{const response=snapshot();response.entries.splice(6,1);const zero={ledger:1000,resultXdr:b64(int(0)),envelopeXdr:new TransactionBuilder(new Account(plan.actors.seller,'10'),{fee:'100',networkPassphrase:plan.networkPassphrase}).addOperation(new Contract(plan.assets[0]).call('balance',new Address(plan.contractId).toScVal())).setTimeout(0).build().toXDR()};const input={plan,response,zeroBalanceEvidence:zero,headerEvidence:header()};assert.equal(initialPublicLifecycleState(input).expected.initialSurplusStroops,'0');assert.throws(()=>initialPublicLifecycleState({...input,zeroBalanceEvidence:null}),/ZERO_EVIDENCE/);assert.throws(()=>initialPublicLifecycleState({...input,zeroBalanceEvidence:{...zero,ledger:999}}),/ZERO_EVIDENCE/);assert.throws(()=>initialPublicLifecycleState({...input,expected:{initialSurplusStroops:'0'}}),/FIELDS/);});
