import test from 'node:test';
import assert from 'node:assert/strict';
import { compareReleaseBody, assertReleaseCsp, assertHtmlCacheControl } from '../release-integrity.mjs';

// Literal bootstrap observed in the saved 2026-09-26 production HTML, not
// generated by the normalizer. Only r and t are challenge-specific values.
const bootstrap = `<script>(function(){function c(){var b=a.contentDocument||(a.contentWindow&&a.contentWindow.document);if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'a40e1be439039ffd',t:'MTc5MDM4MjA5MA=='};var a=document.createElement('script');a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script>`;
const expected = Buffer.from('<!doctype html><body><p>Reviewed app</p></body>');
const withScript = script => Buffer.from(expected.toString().replace('</body>', `${script}</body>`));

test('accepts identical artifact bytes and only the literal observed JSD shape', () => {
  assert.deepEqual(compareReleaseBody(expected, expected).applicationBody, expected);
  const result = compareReleaseBody(withScript(bootstrap), expected, true);
  assert.deepEqual(result.applicationBody, expected);
  assert.equal(result.edgeInjection.raw, bootstrap);
  assert.match(result.edgeInjection.sha256, /^[0-9a-f]{64}$/);
  const rotated = bootstrap.replace('a40e1be439039ffd', '0123456789abcdef').replace('MTc5MDM4MjA5MA==', 'MTc5MDM4MjA5MQ==');
  assert.deepEqual(compareReleaseBody(withScript(rotated), expected, true).applicationBody, expected);
});

test('fails unknown bootstrap additions, mutations, duplicates and invalid challenge values', () => {
  const mutations = [
    bootstrap.replace('if(b){', 'if(b){window.__unreviewedCode=true;'),
    bootstrap.replace('/cdn-cgi/challenge-platform/scripts/jsd/main.js', 'https://unreviewed.example/script.js'),
    bootstrap.replace("a.style.visibility='hidden'", "a.style.visibility='visible'"),
    bootstrap.replace('a40e1be439039ffd', "';window.__unreviewedCode=true;'"),
    bootstrap.replace('MTc5MDM4MjA5MA==', 'QUJDREVGR0hJSg=='),
    bootstrap.replace('MTc5MDM4MjA5MA==', 'MTc5MDM4MjA5MB=='),
    bootstrap + bootstrap,
    `${bootstrap}<script src="https://static.cloudflareinsights.com/beacon.min.js"></script>`,
  ];
  for (const script of mutations) assert.throws(() => compareReleaseBody(withScript(script), expected, true), /artifact mismatch/i);
  assert.throws(() => compareReleaseBody(withScript(bootstrap), expected, false), /artifact mismatch/i);
  assert.throws(() => compareReleaseBody(Buffer.from('altered app'), expected, true), /artifact mismatch/i);
});

test('parses CSP directives and rejects unsafe script keywords independently of token order', () => {
  const good = `default-src 'self'; script-src 'self' 'sha256-${Buffer.alloc(32).toString('base64')}'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'`;
  assert.doesNotThrow(() => assertReleaseCsp(good));
  for (const directive of ['script-src', 'script-src-elem', 'script-src-attr', 'default-src']) {
    for (const keyword of ["'unsafe-inline'", "'unsafe-eval'", "'UNSAFE-INLINE'"]) {
      const policy = directive === 'script-src'
        ? `script-src ${keyword}\t'self'; frame-ancestors 'none'`
        : `script-src 'self'; ${directive} 'self' ${keyword}; frame-ancestors 'none'`;
      assert.throws(() => assertReleaseCsp(policy), /unsafe script/i);
    }
  }
  for (const policy of ['', undefined, "default-src 'self'; frame-ancestors 'none'", "script-src 'self'; frame-ancestors 'none' https:", "script-src 'self'; script-src 'unsafe-inline'; frame-ancestors 'none'"]) {
    assert.throws(() => assertReleaseCsp(policy));
  }
});

test('rejects script source widening even without unsafe-inline or unsafe-eval', () => {
  for (const directive of ['script-src', 'script-src-elem', 'script-src-attr', 'default-src']) {
    for (const source of ['*', 'https:', 'data:', 'blob:', 'https://unreviewed.example', "'nonce-unreviewed'", "'strict-dynamic'", "'sha256-abc='", "'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB='"]) {
      const policy = directive === 'script-src'
        ? `script-src 'self' ${source}; frame-ancestors 'none'`
        : `script-src 'self'; ${directive} 'self' ${source}; frame-ancestors 'none'`;
      assert.throws(() => assertReleaseCsp(policy), /script source/i, policy);
    }
  }
});

test('allows WASM compilation without allowing JavaScript string evaluation', () => {
  assert.doesNotThrow(() => assertReleaseCsp("default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; frame-ancestors 'none'"));
  assert.throws(() => assertReleaseCsp("script-src 'self' 'wasm-unsafe-eval' 'unsafe-eval'; frame-ancestors 'none'"), /unsafe script/i);
  assert.throws(() => assertReleaseCsp("script-src 'self' 'none'; frame-ancestors 'none'"), /script source/i);
});

test('release HTML cache policy requires no-transform and unambiguous immediate revalidation', () => {
  assert.doesNotThrow(() => assertHtmlCacheControl('public, max-age=0, must-revalidate, no-transform'));
  assert.doesNotThrow(() => assertHtmlCacheControl('NO-TRANSFORM, Public, max-age=0, must-revalidate'));
  for (const header of [
    undefined, '', 'public, max-age=0, must-revalidate', 'no-transform',
    'public, max-age=31536000, must-revalidate, no-transform',
    'public, max-age=0, must-revalidate, no-transform, immutable',
    'public, max-age=0, must-revalidate, no-transform, max-age=31536000',
    'public, max-age=0, must-revalidate, no-transform, max-age=0',
    'public, max-age=0, must-revalidate, no-transform,',
    'private, max-age=0, must-revalidate, no-transform',
    'public, max-age=0, must-revalidate, no-transform\r\nX-Other: yes',
  ]) assert.throws(() => assertHtmlCacheControl(header), /HTML Cache-Control/);
});
