import {test} from 'node:test';
import assert from 'node:assert/strict';
import {assertKnownRejectedProbe,readBoundedResponse} from '../verify-testnet-market-catalog.mjs';
function failed(){return {status:'failed',contract:'CCS7FTPT5XGKN7Q6Y3W3EIRPNF5LE7AV2FAVZ4YYERNGUBU24AAMCSPJ',wasmHash:'b1947f2ac6bfa3f42535ed571b956c9fd1ab425b1441adca99d2c8c919ed1c6c',offerId:'7',transactions:[{method:'create_offer',status:'SUCCESS'}],requests:[{label:'wrong-signature',status:503,packet:{signature:'00'.repeat(64)}}]};}
test('resume allows only one known rejected all-zero signature probe after confirmed creation',()=>{assert.doesNotThrow(()=>assertKnownRejectedProbe(failed()));});
test('resume refuses a valid-looking signature even when transport returned503',()=>{const p=failed();p.requests[0].packet.signature='ab'.repeat(64);assert.throws(()=>assertKnownRejectedProbe(p));});
test('resume refuses unresolved or failed creation, unknown request and accepted publication',()=>{for(const status of ['prepared','unresolved','FAILED']){const p=failed();p.transactions[0].status=status;assert.throws(()=>assertKnownRejectedProbe(p));}for(const status of ['unresolved',200,409]){const p=failed();p.requests[0].status=status;assert.throws(()=>assertKnownRejectedProbe(p));}});
test('resume refuses extra signed requests or a different deployment identity',()=>{const a=failed();a.requests.push(a.requests[0]);assert.throws(()=>assertKnownRejectedProbe(a));const b=failed();b.contract='other';assert.throws(()=>assertKnownRejectedProbe(b));const c=failed();c.wasmHash='00'.repeat(32);assert.throws(()=>assertKnownRejectedProbe(c));});
test('bounded response parses a split public JSON packet',async()=>{const encoder=new TextEncoder();const body=new ReadableStream({start(c){c.enqueue(encoder.encode('{\"ok\":'));c.enqueue(encoder.encode('true}'));c.close();}});assert.deepEqual(await readBoundedResponse(new Response(body)),{ok:true});});
test('oversize streamed response is cancelled before unbounded accumulation',async()=>{let cancelled=false;const body=new ReadableStream({start(c){c.enqueue(new Uint8Array(65536));c.enqueue(new Uint8Array(1));},cancel(){cancelled=true;}});await assert.rejects(readBoundedResponse(new Response(body)),/64KiB/);assert.equal(cancelled,true);});
