// Generated by scripts/package-private-prover.mjs --development.
// Public development artifact pins only. Review this source with the release.
// No independent phase2 ceremony or production readiness is claimed.
export const PRIVATE_PROVER_DEVELOPMENT_ONLY = true as const;
export const PRIVATE_PROVER_PROVENANCE = {
  "fixtureManifestSha256": "f40b0cafbd4ee2c94a23b6f7d3873222659dce937106805b725246915a213ef9",
  "dependencyLockSha256": "276ccb368a9405848e1a5032847c5b2d57392ac2032042286ad3330133b5b849",
  "circuitSourceSha256": {
    "transition.circom": "f2493373cd29535b64fb410953459de716e812566c291233dad08f47a7887bd5",
    "revocation.circom": "53c7e30f85b9152a4738afbbad40aca9abc5a41173f8a6d5777f0f9cbf055817",
    "primitives.circom": "e328210aa86370764782d5876bc31e135bd1e023821be870295d80bced69654d",
    "poseidon-encryption.circom": "c090ce7fe7ae288cf853a143051f1de5fb90d31a16f5fc5e0af47f369510aa65"
  }
} as const;
export const PRIVATE_PROVER_ASSETS = {
  "transition": {
    "publicCount": 157,
    "wasm": {
      "bytes": 5626448,
      "sha256": "8a66ec01524cc36aba2f865e8c3c8e72527e6f06dfa1916ab7de4713b0c0776d",
      "chunks": [
        {
          "bytes": 5626448,
          "sha256": "8a66ec01524cc36aba2f865e8c3c8e72527e6f06dfa1916ab7de4713b0c0776d"
        }
      ]
    },
    "zkey": {
      "bytes": 109313645,
      "sha256": "b81e0d963bfee7ce50df8a70ff981f39c4cb39575ad6017b5faf86bf3fbe4ccc",
      "chunks": [
        {
          "bytes": 16777216,
          "sha256": "7b9fa12ff8619def9b2d0e73e44a0453c806a3354ea33b1ec2022d888c22e1ed"
        },
        {
          "bytes": 16777216,
          "sha256": "2e1bb7308add42170c490b613ea14ab39aa91b26250f5fe5e23eddb3dc1fc42a"
        },
        {
          "bytes": 16777216,
          "sha256": "bfaf50cc556d4903a634961d68600549943262d834b130c1e7954a960d5c4989"
        },
        {
          "bytes": 16777216,
          "sha256": "58fcf41bb2fae7a9eff600910b49ddaaced1aaa23006d4490fc44e01eaf710bb"
        },
        {
          "bytes": 16777216,
          "sha256": "7cbe716bac39ee0a0b2edabbdbc2c8e5fb1336bae297349bebddd83afc273c8b"
        },
        {
          "bytes": 16777216,
          "sha256": "fdfe6b8b511724133fefb8d52ada815bdd62a66ed7634097444efebc531d509d"
        },
        {
          "bytes": 8650349,
          "sha256": "a21c0e49e0f0ff7aa7241afe5951ebeeeb81811c7553fd6c465f124fe1d909f3"
        }
      ]
    },
    "verificationKey": {
      "bytes": 33739,
      "sha256": "5ead1dc1a0ee9a0c46e653fa2495faa582f319f06c946d0f9d4a114fb5d1999d",
      "chunks": [
        {
          "bytes": 33739,
          "sha256": "5ead1dc1a0ee9a0c46e653fa2495faa582f319f06c946d0f9d4a114fb5d1999d"
        }
      ]
    }
  },
  "revocation": {
    "publicCount": 4,
    "wasm": {
      "bytes": 2049097,
      "sha256": "53e8ee8e1e1695bdd9b16332d37bcb07ff7ea2dcf19df544fc8709f2a4bd7e08",
      "chunks": [
        {
          "bytes": 2049097,
          "sha256": "53e8ee8e1e1695bdd9b16332d37bcb07ff7ea2dcf19df544fc8709f2a4bd7e08"
        }
      ]
    },
    "zkey": {
      "bytes": 35377101,
      "sha256": "3475f67f1ff258f7dcc52ec75b888af0d5a3ef6e82f1b7c474bc391d4408e124",
      "chunks": [
        {
          "bytes": 16777216,
          "sha256": "82ec7c2c7861498ad3fb0909ce7740395315eff0d27b32a7e7fc04067cf29e14"
        },
        {
          "bytes": 16777216,
          "sha256": "bec4376e2493f7fb72018e5f646a2ec7f38a411bd220c8cda8a69be48f77b545"
        },
        {
          "bytes": 1822669,
          "sha256": "cd5e626bcdf23065fb2be35325f3b2c5b712162b32a3a9d1eb497563d4041475"
        }
      ]
    },
    "verificationKey": {
      "bytes": 3742,
      "sha256": "9310ce15bbc093a102c4dbc2b5740a435a2b930b00ac45d626072e5a6ed36f30",
      "chunks": [
        {
          "bytes": 3742,
          "sha256": "9310ce15bbc093a102c4dbc2b5740a435a2b930b00ac45d626072e5a6ed36f30"
        }
      ]
    }
  }
} as const;
